// Native (host) Unity tests for the portable protocol layer.
//
// Run with:  pio test -e native
//
// The golden vectors below are the exact bytes produced by the Python reference
// implementation (protocol/tests/vectors/frames.json, generated by
// protocol/tests/gen_vectors.py). Keeping both sides pinned to the same vectors
// guarantees firmware and host agree byte-for-byte.

#include <string.h>

#include <unity.h>

#include "protocol/cobs.h"
#include "protocol/crc16.h"
#include "protocol/framing.h"

using namespace protocol;

namespace {

// --- CRC-16/CCITT-FALSE golden values -------------------------------------
void test_crc16_check_value() {
  const uint8_t s[] = {'1', '2', '3', '4', '5', '6', '7', '8', '9'};
  TEST_ASSERT_EQUAL_HEX16(0x29B1, crc16(s, sizeof(s)));
}

void test_crc16_empty() {
  TEST_ASSERT_EQUAL_HEX16(0xFFFF, crc16(nullptr, 0));
}

void test_crc16_single_zero() {
  const uint8_t z = 0x00;
  TEST_ASSERT_EQUAL_HEX16(57840, crc16(&z, 1));
}

// --- COBS round-trip + golden ---------------------------------------------
void test_cobs_roundtrip_various() {
  const size_t sizes[] = {0, 1, 2, 253, 254, 255, 256, 600};
  for (size_t s = 0; s < sizeof(sizes) / sizeof(sizes[0]); ++s) {
    const size_t n = sizes[s];
    uint8_t in[600];
    for (size_t i = 0; i < n; ++i) in[i] = static_cast<uint8_t>((i * 7) & 0xFF);

    uint8_t enc[cobsMaxEncodedLen(600)];
    const size_t enc_len = cobsEncode(in, n, enc, sizeof(enc));
    TEST_ASSERT_TRUE(enc_len > 0 || n == 0 ? true : enc_len > 0);

    // Encoded stream must contain no zero bytes.
    for (size_t i = 0; i < enc_len; ++i) TEST_ASSERT_NOT_EQUAL(0, enc[i]);

    uint8_t dec[600];
    const size_t dec_len = cobsDecode(enc, enc_len, dec, sizeof(dec));
    TEST_ASSERT_EQUAL_UINT(n, dec_len);
    if (n > 0) TEST_ASSERT_EQUAL_HEX8_ARRAY(in, dec, n);
  }
}

void test_cobs_golden_small() {
  // decoded 11220033 -> encoded 0311220233
  const uint8_t dec[] = {0x11, 0x22, 0x00, 0x33};
  const uint8_t want[] = {0x03, 0x11, 0x22, 0x02, 0x33};
  uint8_t enc[16];
  const size_t n = cobsEncode(dec, sizeof(dec), enc, sizeof(enc));
  TEST_ASSERT_EQUAL_UINT(sizeof(want), n);
  TEST_ASSERT_EQUAL_HEX8_ARRAY(want, enc, n);
}

void test_cobs_decode_rejects_zero_code() {
  const uint8_t bad[] = {0x01, 0x00};
  uint8_t out[8];
  TEST_ASSERT_EQUAL_UINT(0, cobsDecode(bad, sizeof(bad), out, sizeof(out)));
}

void test_cobs_decode_rejects_overrun() {
  const uint8_t bad[] = {0x05, 0x11, 0x22};
  uint8_t out[8];
  TEST_ASSERT_EQUAL_UINT(0, cobsDecode(bad, sizeof(bad), out, sizeof(out)));
}

// --- Frame golden encode (vector index 1 from frames.json) ----------------
// msg_type=2 msg_id=0x10 flags=1 seq=0x1234 ts=0x00ABCDEF payload=deadbeef
void test_frame_golden_encode() {
  Header h;
  h.msg_type = 2;
  h.msg_id = 0x10;
  h.flags = 0x01;
  h.seq = 0x1234;
  h.timestamp_ms = 0x00ABCDEF;
  h.payload_len = 4;
  const uint8_t payload[] = {0xDE, 0xAD, 0xBE, 0xEF};

  const uint8_t want[] = {0x00, 0x02, 0xA5, 0x0A, 0x01, 0x02, 0x10, 0x01,
                          0x34, 0x12, 0xEF, 0xCD, 0xAB, 0x02, 0x04, 0x07,
                          0xDE, 0xAD, 0xBE, 0xEF, 0x44, 0x45, 0x00};

  uint8_t out[kMaxWireFrame];
  const size_t n = encodeFrame(h, payload, out, sizeof(out));
  TEST_ASSERT_EQUAL_UINT(sizeof(want), n);
  TEST_ASSERT_EQUAL_HEX8_ARRAY(want, out, n);
}

// --- Frame round-trip ------------------------------------------------------
void test_frame_roundtrip() {
  Header h;
  h.msg_type = 2;
  h.msg_id = 42;
  h.flags = 0x03;
  h.seq = 7;
  h.timestamp_ms = 123456;
  h.payload_len = 5;
  const uint8_t payload[] = {0x10, 0x00, 0x20, 0x00, 0x30};

  uint8_t wire[kMaxWireFrame];
  const size_t n = encodeFrame(h, payload, wire, sizeof(wire));
  TEST_ASSERT_TRUE(n > 0);
  TEST_ASSERT_EQUAL_HEX8(0x00, wire[0]);
  TEST_ASSERT_EQUAL_HEX8(0x00, wire[n - 1]);

  Header out_h;
  uint8_t out_payload[kMaxPayload];
  size_t out_len = 0;
  const DecodeStatus st = decodeFrameBody(wire + 1, n - 2, &out_h, out_payload,
                                          sizeof(out_payload), &out_len);
  TEST_ASSERT_EQUAL(DecodeStatus::Ok, st);
  TEST_ASSERT_EQUAL_UINT(5, out_len);
  TEST_ASSERT_EQUAL_HEX8_ARRAY(payload, out_payload, 5);
  TEST_ASSERT_EQUAL_UINT16(7, out_h.seq);
  TEST_ASSERT_EQUAL_UINT32(123456, out_h.timestamp_ms);
}

// --- Corruption rejection --------------------------------------------------
void test_decode_rejects_bit_flip() {
  Header h;
  h.msg_type = 2;
  h.msg_id = 1;
  h.seq = 1;
  h.timestamp_ms = 10;
  h.payload_len = 3;
  const uint8_t payload[] = {0xAA, 0xBB, 0xCC};

  uint8_t wire[kMaxWireFrame];
  const size_t n = encodeFrame(h, payload, wire, sizeof(wire));

  // Flip a bit inside the encoded body (not a delimiter).
  uint8_t body[kMaxFrameBody + 4];
  memcpy(body, wire + 1, n - 2);
  body[n - 5] ^= 0x01;

  Header out_h;
  uint8_t out_payload[kMaxPayload];
  size_t out_len = 0;
  const DecodeStatus st = decodeFrameBody(body, n - 2, &out_h, out_payload,
                                          sizeof(out_payload), &out_len);
  TEST_ASSERT_NOT_EQUAL(DecodeStatus::Ok, st);
}

void test_decode_rejects_bad_magic() {
  // Build a valid body, corrupt magic, re-COBS it.
  Header h;
  h.payload_len = 0;
  uint8_t wire[kMaxWireFrame];
  const size_t n = encodeFrame(h, nullptr, wire, sizeof(wire));

  uint8_t body[kMaxFrameBody];
  const size_t blen = cobsDecode(wire + 1, n - 2, body, sizeof(body));
  body[0] ^= 0xFF;  // corrupt magic

  uint8_t recobs[kMaxWireFrame];
  const size_t rlen = cobsEncode(body, blen, recobs, sizeof(recobs));

  Header out_h;
  uint8_t out_payload[kMaxPayload];
  size_t out_len = 0;
  const DecodeStatus st = decodeFrameBody(recobs, rlen, &out_h, out_payload,
                                          sizeof(out_payload), &out_len);
  TEST_ASSERT_EQUAL(DecodeStatus::BadMagic, st);
}

void test_decode_rejects_truncation() {
  Header h;
  h.payload_len = 3;
  const uint8_t payload[] = {0x01, 0x02, 0x03};
  uint8_t wire[kMaxWireFrame];
  const size_t n = encodeFrame(h, payload, wire, sizeof(wire));

  Header out_h;
  uint8_t out_payload[kMaxPayload];
  size_t out_len = 0;
  // Pass a too-short body.
  const DecodeStatus st = decodeFrameBody(wire + 1, 5, &out_h, out_payload,
                                          sizeof(out_payload), &out_len);
  TEST_ASSERT_NOT_EQUAL(DecodeStatus::Ok, st);
}

}  // namespace

void setUp() {}
void tearDown() {}

int main(int, char**) {
  UNITY_BEGIN();
  RUN_TEST(test_crc16_check_value);
  RUN_TEST(test_crc16_empty);
  RUN_TEST(test_crc16_single_zero);
  RUN_TEST(test_cobs_roundtrip_various);
  RUN_TEST(test_cobs_golden_small);
  RUN_TEST(test_cobs_decode_rejects_zero_code);
  RUN_TEST(test_cobs_decode_rejects_overrun);
  RUN_TEST(test_frame_golden_encode);
  RUN_TEST(test_frame_roundtrip);
  RUN_TEST(test_decode_rejects_bit_flip);
  RUN_TEST(test_decode_rejects_bad_magic);
  RUN_TEST(test_decode_rejects_truncation);
  return UNITY_END();
}
